<form method="POST" action="login/auth" >
              <div class="d-flex flex-row align-items-center justify-content-center justify-content-lg-start">
              </div>
              <div class="divider d-flex align-items-center my-4">
              </div>

              <!-- Email input -->
              <div class="form-outline mb-4">
                <input type="email" id="form3Example3" class=" form-control-lg" placeholder="Enter a valid email address" name="email" />
                
              </div>

              <!-- Password input -->
              <div class="form-outline mb-3">
                <input type="password" id="form3Example4" class=" form-control-lg" placeholder="Enter password" name="pass" />
                
              </div>
              <div class=" text-lg-start mt-4 pt-2">
                <button type="submit" class="btn btn-primary btn-lg" style="padding-left: 2.5rem; padding-right: 2.5rem;" name="userlogin">Login</button>
                <p> 
              <?php echo $this->tag->checkField(['remember','value' => 'rem',]); ?>
              <label for="terms">Remember Me</label>
                </p>
                <p class="small fw-bold mt-2 pt-1 mb-0">Don't have an account? <a href="../login/signup" class="link-danger">Register</a></p>
              </div>
            
            </form>



