
<?php
if ($settings->count() > 0) {
    ?>
   
    <a href="#" class="nav-link" id="user" ><h4>Settings</h4></a>
    <div id="userdiv">
    <table class="table table-bordered table-hover">
        <thead class="thead-light">
        <tr>
            
            <th>Default Price</th>
            <th>Default Stock</th>
            <th>Default Zipcode</th>
            <th>Default Category </th>
            <th>Default Quantity </th>
            
            
            
        </tr>
        </thead>
       
        <tbody>
        <?php foreach ($settings as $setting) { ?>
            <tr>
               
                <td><?php echo $setting->default_price; ?></td>
                <td><?php echo $setting->default_stock ?></td>  
                <td><?php echo $setting->default_zip ?></td> 
               
                 <td> 
                 <?php echo $setting->default_category ?>
                  </td>
                  <td> 
                 <?php echo $setting->default_user_order_quantity ?>
                  </td>
                 
                </form>
                  
                
                
        <?php } ?>
        </tbody>
    </table>
    </div>

    <?php
}

?>