
<nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container px-4 px-lg-5">
            <a class="navbar-brand" href="#!"><b>Shopingo</b></a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav me-auto mb-2 mb-lg-0 ms-lg-4">
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="#!">Home</a></li>
                    
                    <li class="nav-item"><a class="nav-link active" aria-current="page" href="dashboard?bearer=<?php echo $_GET['bearer'];?>">Dashboard</a></li>
                    <li class="nav-item"><a class="nav-link active" href="#!">About</a></li>
                    <input class="form-control mr-sm-2" type="hidden" placeholder="category" aria-label="Search" id="serinput" name="serinput" >
                    </li>
                    <li class="nav-item">
                        <!-- <button class="btn btn-outline-success my-2 my-sm-0"  name="btnfilt" id="btnfilt" >Search</button></form> -->
                    </li></form>

                </ul>
                <form class="d-flex " method="POST" action="">
                    
                <a class="btn " href="#">
                        <i class="fa fa-user"></i>
                        <?php  $username = $this->session->get('username');
                        echo $username;  ?>
                    </a>
                

                     <a class="btn btn-outline-dark" href="addtocart?bearer=<?php echo $_GET['bearer'] ?>">
                        <i class="bi-cart-fill me-1"></i>
                        Cart
                        <span class="badge bg-dark text-white ms-1 rounded-pill"><?php if($this->session->has('username')) {echo $carts->count(); }?></span>
                    </a> 
    
     <?php if($this->session->has('username')){
    echo ' <a class="btn btn-outline-danger my-2 my-sm-0 rounded-pill" style="margin-left: 2px;" href="login/logout" >Log Out</a>';

     }
     else{
        echo ' <a class="btn btn-outline-danger my-2 my-sm-0 rounded-pill" style="margin-left: 2px;" href="login" >Log In</a>';

     }
     ?>

                </form>
            </div>
        </div>
    </nav>
    <header class=" ">
        <div class="container">
            <div class="text-center text-white">
                <img src="../../../public/img/onlineshopping.jpg" class="w-100 " height="300" alt="">

            </div>
        </div>
    </header>
    <section class="py-5" id="divcard" >
        
            
             <div class="container-fluid mt-4 mb-5">

                <div class="row justify-content-center" >
                    
                
      <?php   if ($products->count() > 0) {
          foreach($products as $product){
          ?>     
                        <div class="col-3 mt-4">
                         <div class="card">
                         <img src="../../../public/img/<?php echo $product->product_image; ?>" alt="...   ">
                          <div class="card-body">
                         <span class="card-title"><b><?php  echo $product->product_name ?></b></span>
                        <span class="card-text"><small><?php  echo $product->product_category ?></small></span>
                        <div class=" ">
                        <span class=" text-danger"><b>Rs<?php  echo $product->price ?></b></span>
                     </div>
                        <div class="card-footer p-4 pt-0 border-top-0 bg-transparent">
                        <form method="POST" action="neworder?bearer=<?php echo $_GET['bearer'] ?>"><div class="text-center"><button class="btn btn-outline-success mt-auto border-0" value="<?php  echo $product->productId ?>"  name="neworder" >Buy Now</button></form></div>
                        <form method="POST" action="addtocart/atocart?bearer=<?php echo $_GET['bearer'] ?>"> <div class="text-center"><button class="btn btn-outline-danger mt-1" value="<?php  echo $product->productId ?>"  name="addtocart" >Add To Cart</button></form></div>
                        <!-- <div class="text-center mt-1"><button class="btn btn-outline-danger border-0 mt-auto" value="'.$v["productId"].'"  name="moreinfo" >more info</button></div> -->
                    </div>
                    </div>
                </div>
            </div>
                      <?php }?>
                    
                </div>
            </div>
            <?php } ?> 
</section>