<a class="btn " href="addproduct?bearer=<?php echo $_GET['bearer'] ?>" >Add Product</a><br>
<a class="btn " href="products?bearer=<?php echo $_GET['bearer'] ?>" >Products</a><br>
<a class="btn " href="orders?bearer=<?php echo $_GET['bearer'] ?>" >Orders</a><br>
<a class="btn " href="settings?bearer=<?php echo $_GET['bearer'] ?>" >Settings</a><br>
<a class="btn " href="component?bearer=<?php echo $_GET['bearer'] ?>" >Component</a><br>
<a class="btn " href="dashboard/manager?bearer=<?php echo $_GET['bearer'] ?>" >Managers</a><br>